// NexusOS Whitepaper — kind-30023 Nostr article content
// Keep backtick code fences as raw strings to avoid template-literal collision

export const WHITEPAPER_SLUG    = "nexusos-whitepaper-v1";
export const WHITEPAPER_TITLE   = "NexusOS: A Physics-Native OS for a Kardashev Type I Civilization";
export const WHITEPAPER_SUMMARY =
  "NexusOS replaces cryptographic hashing with electromagnetic wave physics. " +
  "E=hf governs fees. Ψ channels replace IP addresses. " +
  "WavelengthScript runs on silicon today, photonics in 2032. " +
  "85M NXT Nostr Advocacy Airdrop live now at wnsp.io/airdrop";

const FENCE = "```";

export const WHITEPAPER_CONTENT = [
  "# NexusOS: A Physics-Native Operating System for a Kardashev Type I Civilization",
  "",
  "*First public disclosure: 2026-05-16 · AGPL-3.0*",
  "",
  "---",
  "",
  "## Abstract",
  "",
  "Every blockchain in existence today is built on a cryptographic scaffold designed for silicon transistors. When photonic computing arrives — and it will, circa 2032 — none of that infrastructure translates. The entire stack must be rewritten.",
  "",
  "NexusOS is written in the language of the destination hardware from day one.",
  "",
  "Instead of SHA-256 we use **Maxwell's equations**. Instead of private keys we use **spectral wavelength addresses**. Instead of proof-of-work consuming arbitrary compute cycles, we use **E = hf** to derive transaction costs from the actual physics of information transmission.",
  "",
  "---",
  "",
  "## The Foundation: Theory of Compression States",
  "",
  "The universe's complexity emerges from a single principle — the first unobserved oscillation. A quantum state that cannot collapse because no observer exists to measure it. This yields the **Compression State equation**:",
  "",
  FENCE,
  "Λ = hf / c²",
  FENCE,
  "",
  "- **Λ** = compression mass — the information density of a quantum state",
  "- **h** = Planck's constant (6.626 × 10⁻³⁴ J·s)",
  "- **f** = oscillation frequency",
  "- **c** = speed of light",
  "",
  "Different frequencies encode different compression states. Higher frequency = higher photon energy = higher authority in the network. This is not a design choice. It is physics.",
  "",
  "---",
  "",
  "## WNSP: Wave Network Spectral Protocol",
  "",
  "WNSP replaces numerical IP addresses with **spectral addresses** — unique positions in the electromagnetic spectrum:",
  "",
  FENCE,
  "Ψ(wdm, oam, pol)",
  FENCE,
  "",
  "A point in 3-dimensional Hilbert space defined by:",
  "- **WDM** — wavelength-division multiplexing band (256 values, 380–780 nm)",
  "- **OAM** — orbital angular momentum mode (50 modes)",
  "- **Pol** — polarisation state (H or V)",
  "",
  "256 × 50 × 2 = **25,600 orthogonal communication channels**",
  "",
  "These channels are orthogonal by quantum mechanics: **⟨Ψᵢ|Ψⱼ⟩ = 0**. Channel isolation is enforced by physics, not software policy. No collision is possible in principle.",
  "",
  "### WNSP-URI v1.0",
  "",
  FENCE,
  "wnsp://Ψ(128,25,H)/documents/whitepaper",
  FENCE,
  "",
  "DNS-free. Censorship-proof. No ICANN. No registrar. No government can deregister a wavelength.",
  "",
  "---",
  "",
  "## Authority Bands",
  "",
  "The network enforces four authority tiers, each anchored in the electromagnetic spectrum:",
  "",
  "| Band   | Spectrum Region | Energy    | Role                         |",
  "|--------|-----------------|-----------|------------------------------|",
  "| SYSTEM | UV / X-ray      | Highest   | Protocol genesis & bootstrap |",
  "| KERNEL | Violet–Blue     | Very high | AI OS kernel agents          |",
  "| USER   | Green–Orange    | Medium    | Standard participant nodes   |",
  "| GUEST  | Red–IR          | Lowest    | Unauthenticated observers    |",
  "",
  "Higher authority = shorter wavelength = higher photon energy per Maxwell's equations.",
  "",
  "---",
  "",
  "## Physics-Based Transaction Fees",
  "",
  FENCE,
  "fee = base_fee × (E_sender / E_reference)",
  "    where E_sender = h × f_sender",
  FENCE,
  "",
  "Your transaction cost is proportional to your spectral energy. A KERNEL-band node pays more than a USER-band node because it operates at higher frequency. The ledger doesn't run on trust — it runs on thermodynamic consistency.",
  "",
  "**NXT fees are never burned.** They flow to the orbital treasury to fund the physical hardware roadmap.",
  "",
  "---",
  "",
  "## WavelengthScript & WNSP VM",
  "",
  "**WavelengthScript** is a compiled language for spectral-native computation. Programs describe operations in terms of wavelengths, channels, and compression states. Each Ψ channel acts as a spectral register.",
  "",
  "**WNSP VM** — a bytecode interpreter running today in browser and server environments. Every instruction maps to a physical wave operation.",
  "",
  "Write once. Run on silicon today. Run on photonics in 2032. No architecture rewrite needed.",
  "",
  "---",
  "",
  "## CE Encoding: Text → Physics",
  "",
  "Every character maps to a unique wavelength in the visible spectrum:",
  "",
  FENCE,
  "ceEncode('A') → { wavelength: 461.7 nm, band: \"BLUE\", energy: 4.31 × 10⁻¹⁹ J }",
  FENCE,
  "",
  "128 spectral bands covering 380–780 nm (3.125 nm resolution per band). Published as open-source packages:",
  "",
  "- **npm**: `npm install nexusos-ce-encoder`",
  "- **pip**: `pip install git+https://github.com/nexusosdaily-code/NexusOS#subdirectory=packages/ce-encoder-py`",
  "",
  "Both produce bit-identical output for the same input. AGPL-3.0.",
  "",
  "---",
  "",
  "## Photonic Computing Vision (~2032)",
  "",
  "Silicon is the **bridge encoder**. Every CE lookup that today runs as a table scan in RAM will execute as a physical wavelength selection in a photonic waveguide.",
  "",
  "The 25,600 orthogonal Ψ channels map directly to physical hardware lanes. When photonic ASICs arrive, NexusOS doesn't need a migration — it *is* the photonic architecture, running on simulation hardware in the interim.",
  "",
  "The stack is already written in the language of the destination. We are building the software, then the hardware to run it natively.",
  "",
  "---",
  "",
  "## Hardware Roadmap",
  "",
  "1. **SNIC** — Spectral Network Interface Card: replaces Ethernet with WDM optical I/O",
  "2. **PHR-1** — Photonic Hash Register: executes WNSP compression state lookups at ~2 THz clock speeds",
  "3. **Spectral Relay Mesh v1** — physical network of WNSP relay nodes replacing TCP/IP backbones",
  "4. **Target horizon**: ~2032 photonic ASICs that speak natively in wavelengths",
  "",
  "---",
  "",
  "## NXT Token",
  "",
  "| Property   | Value                             |",
  "|------------|-----------------------------------|",
  "| Supply     | 21,000,000,000 NXT (21 billion)   |",
  "| Sub-unit   | 1 NXT-sat = 0.00000001 NXT        |",
  "| Fee model  | Physics-proportional (E = hf)     |",
  "| Fee routing| Orbital treasury → hardware fund  |",
  "| Burned?    | Never — indestructible            |",
  "",
  "NXT is the mechanism by which the community crowdfunds physical WNSP hardware: SNIC, PHR-1, and Spectral Relay Mesh v1. Every token held is a stake in the photonic future.",
  "",
  "---",
  "",
  "## 🎁 85,000,000 NXT Nostr Advocacy Airdrop",
  "",
  "We are distributing **85 million NXT** to Nostr advocates who help bring physics-native networking to the world.",
  "",
  "**1,000 NXT per wallet · 85,000 claims · first-come, first-served**",
  "",
  "**To claim in ~10 seconds:**",
  "1. Go to **wnsp.io/airdrop**",
  "2. Click *Sign in with Nostr* — one signature with Alby or nos2x",
  "3. Your spectral wallet and Ψ channel are assigned automatically",
  "4. 1,000 NXT appears in your wallet instantly",
  "",
  "No email. No form. No KYC. Just your Nostr key.",
  "",
  "---",
  "",
  "*Built on the Theory of Compression States.*",
  "*First public disclosure: 2026-05-16.*",
  "*AGPL-3.0 · wnsp.io · Ψ(52,3,V)*",
  "",
  "**#nexusos #wnsp #nxt #nostr #bitcoin #photonics #physics #blockchain**",
].join("\n");
